# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from csv.`/Volumes/juan_dev/ml/data/inputs/insurance/insurance.csv` limit 10

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM juan_dev.ml.insurance_bronze"))

# COMMAND ----------

# MAGIC %md
# MAGIC # Silver

# COMMAND ----------

df = spark.table("juan_dev.ml.insurance_silver").toPandas()
    
# Healthcare-specific data profiling
eda_results = {
    "total_patients": len(df),
    "avg_age": df['age'].mean(),
    "smoker_percentage": (df['smoker'].sum() / len(df)) * 100,
    "high_cost_threshold": df['charges'].quantile(0.95),
    "missing_data_percentage": (df.isnull().sum() / len(df)) * 100
}

# COMMAND ----------

print(eda_results)

# COMMAND ----------

